sudo: required

language: python

python:
  - "3.7"
dist: xenial

before_install:
  - docker build -t sample docker/
  - docker sudo docker run -it --rm --name py_container -v `pwd`:/var/src sample

script:
  - docker ps -a


# before_install:
#   - pip install pipenv
#   - pipenv install

script:
  - pytest tests
  - mypy imaginary_number/
  - flake8 tests/ imaginary_number/

