sudo: required

language: python

python:
  - "3.7"
dist: xenial

before_install:
  - pip install poetry
  - poetry install

script:
  - pytest tests
  - mypy imaginary_number/
  - flake8 tests/ imaginary_number/
